# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QR_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QLabel
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import QTimer

from Menu import Ui_Menu_Food

class Ui_QR_WinDow(object):
    def setupUi(self, QR_WinDow):
        QR_WinDow.setObjectName("QR_WinDow")
        QR_WinDow.resize(535, 554)
        self.centralwidget = QtWidgets.QWidget(QR_WinDow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 531, 501))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(6)
        self.label.setObjectName("label")
        QR_WinDow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QR_WinDow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 535, 26))
        self.menubar.setObjectName("menubar")
        QR_WinDow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QR_WinDow)
        self.statusbar.setObjectName("statusbar")
        QR_WinDow.setStatusBar(self.statusbar)

        self.retranslateUi(QR_WinDow)
        QtCore.QMetaObject.connectSlotsByName(QR_WinDow)

        # Set the QR image
        self.setQRImage('D:\\internship\\Project\\Tablet_menu\\UI_TABLET_MENU\\img\\ND7686.png')

    def retranslateUi(self, QR_WinDow):
        _translate = QtCore.QCoreApplication.translate
        QR_WinDow.setWindowTitle(_translate("QR_WinDow", "QR Window"))
        self.label.setText(_translate("QR_WinDow", ""))  # Remove the placeholder text

    def setQRImage(self, image_path):
        pixmap = QPixmap(image_path)
        self.label.setPixmap(pixmap)
        self.label.setScaledContents(True)  # Scale the pixmap to fit the label size
        QTimer.singleShot(10000, self.switchToNewWindow)  # Wait 10 seconds and switch to new window

    def switchToNewWindow(self):
        print("Switching to new window...")  # Thêm dòng này để kiểm tra
        self.menuWindow = Ui_Menu_Food()

        self.menuWindow.show()
        QR_WinDow.close()  # Đóng cửa sổ hiện tại


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QR_WinDow = QtWidgets.QMainWindow()
    ui = Ui_QR_WinDow()
    ui.setupUi(QR_WinDow)
    QR_WinDow.show()
    sys.exit(app.exec_())
